Repository brownfield-team/anacapa-github-linker, pull requests merged in 2020-03, with the labels that each got.

#178 Superficially removed outward facing references to perm with student ID
  app/assets/javascripts/courses.js
  app/models/roster_student.rb
  app/views/courses/_show_admin.html.erb
Labels: improvement

#182 add labels to users index (closed #181)
  app/views/users/index.html.erb
Labels: improvement

#179 Added repository autogeneration for GitHub teams
  app/controllers/courses/teams_controller.rb
  app/controllers/courses_controller.rb
  app/jobs/course/create_team_repos_job.rb
  app/jobs/course/refresh_github_teams_job.rb
  app/jobs/course/students_org_membership_check_job.rb
  app/jobs/course/update_github_repos_job.rb
  app/models/course.rb
  app/models/github_repo.rb
  app/models/org_team.rb
  app/models/repo_team_contributor.rb
  app/models/roster_student.rb
  app/models/student_team_membership.rb
  app/views/courses/_show_admin.html.erb
  app/views/courses/repos.html.erb
  app/views/courses/teams/create_repos.html.erb
  app/views/courses/teams/show.html.erb
  config/routes.rb
  db/migrate/20200223083942_create_org_teams.rb
  db/migrate/20200223084157_create_repo_team_contributors.rb
  db/migrate/20200223093457_add_team_id_to_org_team.rb
  db/migrate/20200313070459_create_students_teams_table.rb
  db/migrate/20200313074330_add_slug_to_org_teams.rb
  db/schema.rb
  test/fixtures/org_teams.yml
  test/fixtures/repo_team_contributors.yml
  test/models/course_test.rb
  test/models/org_team_test.rb
  test/models/repo_team_contributor_test.rb
Labels: feature

#187 Squashed old migrations prior to feb 2020
  db/migrate/20171116213150_create_courses.rb
  db/migrate/20171116220101_create_users.rb
  db/migrate/20171124201455_add_devise_to_users.rb
  db/migrate/20180113222424_create_join_table_users_courses.rb
  db/migrate/20180114004551_rolify_create_roles.rb
  db/migrate/20180114072443_create_roster_students.rb
  db/migrate/20180114072530_add_course_to_roster_student.rb
  db/migrate/20180119002524_add_user_id_to_roster_students.rb
  db/migrate/20180119233806_drop_courses_users.rb
  db/migrate/20180223231254_add_roster_student_unique_constraints.rb
  db/migrate/20180307221702_add_enrolled_to_roster_students.rb
  db/migrate/20190726203820_add_hidden_to_courses.rb
  db/migrate/20191120012103_create_completed_jobs.rb
  db/migrate/20191120023222_add_course_ref_to_completed_jobs.rb
  db/migrate/20191120023633_remove_time_run_from_completed_jobs.rb
  db/migrate/20191120054002_add_is_org_member_to_roster_students.rb
  db/migrate/20191120061955_add_summary_to_completed_jobs.rb
  db/migrate/20191121012950_create_github_repos.rb
  db/migrate/20191121014543_create_join_table_github_repos_users.rb
  db/migrate/20191121031312_add_repo_id_to_github_repos.rb
  db/migrate/20191217021033_add_short_name_to_completed_jobs.rb
  db/migrate/20200104072015_add_full_name_to_github_repos.rb
  db/migrate/20200104085704_create_repo_contributors_table.rb
  db/migrate/20200104214922_drop_github_repos_users.rb
  db/migrate/20200106180359_change_columns_of_repo_contributors.rb
  db/migrate/20200106180359_init_schema.rb
Labels: Infrastructure

#192 Slack integration including associating with course, students, and bot
  Gemfile
  Gemfile.lock
  app/controllers/courses/slack_controller.rb
  app/controllers/courses_controller.rb
  app/controllers/slack/auth_controller.rb
  app/controllers/slack/commands_controller.rb
  app/jobs/admin/purge_completed_jobs_job.rb
  app/jobs/admin/purge_unused_users_job.rb
  app/jobs/background_job.rb
  app/jobs/course/associate_slack_users_job.rb
  app/jobs/course/create_team_repos_job.rb
  app/jobs/course/purge_course_repos_job.rb
  app/jobs/course/refresh_github_teams_job.rb
  app/jobs/course/students_org_membership_check_job.rb
  app/jobs/course/test_job.rb
  app/jobs/course/update_github_repos_job.rb
  app/jobs/course_job.rb
  app/models/ability.rb
  app/models/course.rb
  app/models/roster_student.rb
  app/models/slack_user.rb
  app/models/slack_workspace.rb
  app/views/courses/_show_admin.html.erb
  app/views/courses/slack/show.html.erb
  config/routes.rb
  db/migrate/20200327041537_create_slack_workspace_table.rb
  db/migrate/20200327085909_add_scope_to_slack_workspaces.rb
  db/migrate/20200327184318_rename_access_token_in_slack_workspaces.rb
  db/migrate/20200327201336_configure_relationship_between_workspace_and_course.rb
  db/migrate/20200327212103_create_slack_users.rb
  db/migrate/20200327234145_add_slack_workspace_id_to_slack_users.rb
  db/schema.rb
  dotenv.example
Labels: feature

#195 Minor patches to Slack integration
  app/jobs/course/associate_slack_users_job.rb
  app/models/slack_user.rb
  app/views/courses/_show_admin.html.erb
  app/views/courses/roster_students/show.html.erb
  app/views/courses/slack/show.html.erb
  test/controllers/roster_students_controller_test.rb
Labels: bugfix

#197 Minor UI changes to show student page, associate slack users job now runs when slack added to course
  app/assets/stylesheets/application.scss
  app/controllers/slack/auth_controller.rb
  app/views/courses/roster_students/show.html.erb
Labels: improvement
